// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"
)

type StartPageReminder struct {
	ID        int64
	Text      string
	Completed bool
	CreatedAt time.Time
}

type StartPageSection struct {
	ID       int64
	Title    string
	Position int64
}

type StartPageSectionItem struct {
	ID        int64
	Title     string
	Url       string
	SectionID int64
}
